### ISSUE TITLE
Consider to use provided scope for vertx-core

### ISSUE THREAD

**Issue by bmsantos** [cescoffier/vertx-completable-future#2]
I'm using this library with future graphql async library that uses Java's CompletableFuture.
I'm also using vertx 3.3.3 and have to exclude vertx-core 3.3.2 from maven.

Setting the dependency scope to "provided" would remove the need for dependency exclusions in projects using vertx other than 3.3.2.

```xml
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-core</artifactId>
      <scope>provided</scope>
    </dependency>
```

**Comment by cescoffier** [comment]
Just cut the 0.1.1 release with the fix. Should be in Maven central in a few minutes.

**Comment by bmsantos** [comment]
Thanks
