### ISSUE TITLE
why exceptionally is not implemented in VertxCompletableFuture

### ISSUE THREAD

**Issue by StarWindMoonCloud** [cescoffier/vertx-completable-future#42]
any good reasoning here, exceptionally is very handy to me.

**Comment by cescoffier** [comment]
It's just because I forgot. Fancy a PR?

**Comment by StarWindMoonCloud** [comment]
@cescoffier I took a look at the code, but not sure how to implement here, could you please help out?

**Comment by AndierZ** [comment]
I might be able to help. Let me take a poke at it. Btw this is great work. Kudos to the team and @cescoffier for creating this utility.

**Comment by StarWindMoonCloud** [comment]
so any update? @AndierZ

**Comment by jayfeng0625** [comment]
I have got a branch with the implementation but I was unable to push due to permission. @cescoffier would you mind sharing some guidelines on how to contribute?
