### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by jklingsporn** [cescoffier/vertx-completable-future#45]
I just wanted to ask what the state of the project is in terms of the current and upcoming vertx releases. As vertx `Futures` now have a `toCompletionStage`-method it makes this project more or less obsolete? Or will parts of this project be merged into `vertx-core`? Or will the functionality to wrap external, a.k.a non-event-loop-`CompletableFutures` not be merged into the core?

**Comment by cescoffier** [comment]
Unfortunately, I don't have the time to maintain this project. 

I don't believe it would be part of Vert.x, and in terms of API, I'm not recommending CompletionStage anymore after having seen quite some code horrors. 

That's being said, if someone wants to continue this project, I would be happy to provide access!
